### ISSUE TITLE
Agregar un sidebar element con el listado de canales en Slack

### ISSUE THREAD

**Issue by 3manuek** [canalDBA/canaldba.github.io#5]
Idealmente deberíamos poder generarlo dinámicamente en tiempo de build. *idealmente*

Pero se acepta un harcoding decente.

**Comment by Ctrl4** [comment]
"Canales de slack" que al clickear baje la lista de canales?

**Comment by 3manuek** [comment]
Si querés hacer la lista dinámica, habría que hacer un script que haga el query al servicio de Slack y genere el listado. Recordá que es HTML estático, ya que está servido en GH pages.

Igualmente, para salir del paso yo harcodearía el listado. Esto se puede hacer simple agregando un .html raíz y siguiendo los templates de los ya existentes. (Con esto, jekyll genera un elemento en el sidebar).

**Comment by Ctrl4** [comment]
Voy por hardcodearlo ajjaja.

Canales general purpose o todos los canales?

**Comment by Ctrl4** [comment]
Agregué una carpeta _data con un channels.yml donde agregando nombre del canal y la url se agregaría a la lista de canales. En un futuro no muy lejano se podría empezar a desarrollar ese script que revise los canales y lo agregue a channels.yml

```
- name: aleatorio
  url: slack://channel?id=C7D88D2NN&team=T7CJH7Y9W
```

Decidí ir por la url de la aplicación de Slack, pero si es mejor usar la url web se cambia sin problemas.
También si se prefiere otro formato(json, csv) en vez de yml es el momento de decirlo.

**Comment by 3manuek** [comment]
Un yml va muy bien para esto, me pareció buena la idea de un _data, totalmente. Esto también puede usarse para los posts, así que genial. Hice unos cambios, miralo y mergeamos.

**Comment by Ctrl4** [comment]
Me parece bien!
